- type: startingGear
  id: OxygenBreather
  abstract: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Arachne
    - Arachnid
    - Chitinid
    - Diona
    - Dwarf
    - Felinid
    - Gingerbread
    - Harpy
    - Human
    - Lamia
    - Moth
    - Oni
    - Reptilian
    - Shadowkin
    - SynthHuman
    - Tajaran
    - Thaven
    - Vulpkanin

- type: startingGear
  id: NitrogenBreather
  abstract: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - SlimePerson
    - Vox

- type: startingGear
  id: PlasmaBreather
  abstract: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Plasmaman

- type: startingGear
  id: WaterVaporBreather
  abstract: true
  requirements:
  - !type:CharacterSpeciesRequirement
    species:
    - Feroxi